#!/usr/bin/env python3
"""
Composed Agent: youtube-research-learner
Auto-generated by SkillComposer from: youtube-research, youtube-transcript, video-learner
"""

import sys
import os
import json
from typing import Dict
from pathlib import Path
from importlib.util import spec_from_file_location, module_from_spec

HERMES_HOME = Path(os.environ.get("HERMES_HOME", "D:/Portable_Soft/hermes"))
SKILLS_DIR = HERMES_HOME / "skills"


class ComposedAgent_youtube_research_learner:
    """Composed agent: youtube-research -> youtube-transcript -> video-learner"""

    def __init__(self):
        self.context = {}
        self.handoff_data = {}

    def execute(self, goal: str, context: str = "") -> Dict:
        """Execute the composed agent."""
        self.context = {"goal": goal, "context": context}

        steps = [
            {"step": 1, "skill": "youtube-research", "input_from": "user", "output_to": "youtube-transcript", "handoff_key": "step_1_output", "preserve_context": True},
            {"step": 2, "skill": "youtube-transcript", "input_from": "youtube-research", "output_to": "video-learner", "handoff_key": "step_2_output", "preserve_context": True},
            {"step": 3, "skill": "video-learner", "input_from": "youtube-transcript", "output_to": "user", "handoff_key": "step_3_output", "preserve_context": True}
        ]

        for step in steps:
            skill_name = step["skill"]
            input_from = step["input_from"]

            # Get input from previous step
            step_input = self.context.get("goal", "")
            if input_from != "user" and input_from in self.handoff_data:
                step_input = self.handoff_data[input_from]

            # Add context from handoff
            full_context = f"""
ORIGINAL GOAL: {goal}
PREVIOUS RESULT: {step_input}
CURRENT STEP: {skill_name}
HANDOFF KEY: {step.get("handoff_key", "")}
"""

            # Execute skill via subagent
            result = self._execute_skill(skill_name, full_context, goal)

            if not result.get("success"):
                return {"success": False, "error": f"Step {skill_name} failed: {result.get('error')}"}

            # Store handoff data
            handoff_key = step.get("handoff_key", f"{skill_name}_output")
            self.handoff_data[handoff_key] = result.get("stdout", "")
            self.context[skill_name] = result

            # Preserve context for next step
            if step.get("preserve_context"):
                self.context["partial_results"] = self.handoff_data

        return {"success": True, "result": self.handoff_data, "context": self.context}

    def _execute_skill(self, skill_name: str, context: str, goal: str) -> Dict:
        """Execute a skill directly by importing its main module."""
        # Try multiple possible locations
        possible_paths = [
            SKILLS_DIR / skill_name,
            SKILLS_DIR / "media" / skill_name,
            SKILLS_DIR / "autonomy" / skill_name,
            SKILLS_DIR / "devops" / skill_name,
        ]

        skill_dir = None
        for path in possible_paths:
            if path.exists():
                skill_dir = path
                break

        if not skill_dir:
            return {"success": False, "error": f"Skill {skill_name} not found in any known location"}

        # Find main script
        scripts_dir = skill_dir / "scripts"
        if scripts_dir.exists():
            for script_file in scripts_dir.glob("*.py"):
                try:
                    spec = spec_from_file_location(f"skill_{skill_name}", script_file)
                    module = module_from_spec(spec)
                    spec.loader.exec_module(module)
                    if hasattr(module, 'main'):
                        try:
                            # Try to call main with context if it accepts args
                            import inspect
                            sig = inspect.signature(module.main)
                            if len(sig.parameters) > 0:
                                module.main(context)
                            else:
                                module.main()
                            return {"success": True, "stdout": f"Executed {script_file.name}", "stderr": "", "returncode": 0}
                        except SystemExit:
                            return {"success": True, "stdout": f"Executed {script_file.name} (exited)", "stderr": "", "returncode": 0}
                        except Exception as e:
                            return {"success": False, "error": f"Error in {script_file.name}: {e}"}
                except Exception as e:
                    continue
            return {"success": True, "stdout": f"Skill {skill_name} found, no main() in scripts", "stderr": "", "returncode": 0}
        else:
            return {"success": True, "stdout": f"Skill {skill_name} found, no scripts dir", "stderr": "", "returncode": 0}


def main():
    if len(sys.argv) < 2:
        print("Usage: python composed_agent.py <goal> [context]")
        sys.exit(1)

    goal = sys.argv[1]
    context = sys.argv[2] if len(sys.argv) > 2 else ""

    agent = ComposedAgent_youtube_research_learner()
    result = agent.execute(goal, context)
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()